tap "heroku/brew"
tap "homebrew/science"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/x11"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jawshooah/pyenv"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
tap "kylef/formulae"
tap "neovim/neovim"
tap "universal-ctags/universal-ctags"
cask "java"
cask "xquartz"
brew "ack"
brew "gmp"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "veclibfort"
brew "arpack"
brew "readline"
brew "augeas"
brew "autoconf"
brew "automake"
brew "aws-elasticbeanstalk"
brew "sqlite"
brew "xz"
brew "azure-cli"
brew "bfg"
brew "bison"
brew "cabal-install"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "pcre"
brew "dialog"
brew "certbot"
brew "cloc"
brew "cmake"
brew "convox"
brew "coreutils"
brew "cscope"
brew "curl"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "libtool"
brew "dnscrypt-proxy"
brew "wxmac"
brew "elixir"
brew "ghostscript"
brew "epstool"
brew "lame"
brew "git"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "fftw"
brew "fig2dev"
brew "fish"
brew "fltk"
brew "freexl"
brew "fswatch"
brew "gawk"
brew "gd"
brew "geos"
brew "json-c"
brew "proj"
brew "liblwgeom"
brew "libxml2"
brew "libspatialite"
brew "gdal"
brew "gl2ps"
brew "glpk"
brew "gnu-sed"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "gnuplot", args: ["with-aquaterm"]
brew "go"
brew "pkg-config"
brew "gpg-agent"
brew "gpp"
brew "graphicsmagick"
brew "graphviz"
brew "haskell-stack"
brew "szip"
brew "hdf5"
brew "htop"
brew "imagemagick"
brew "iperf3"
brew "jemalloc"
brew "ledger"
brew "lftp"
brew "libevent"
brew "libpst", args: ["with-python"]
brew "libssh2"
brew "libtermkey"
brew "libusb-compat"
brew "libuv"
brew "libvterm"
brew "libyaml"
brew "llvm"
brew "lzip"
brew "lzlib"
brew "lzo"
brew "m-cli"
brew "macvim", args: ["with-override-system-vim"]
brew "mas"
brew "memcached", restart_service: true
brew "metis"
brew "mitmproxy"
brew "mono", args: ["without-fsharp"]
brew "mpv"
brew "msgpack"
brew "unibilium"
brew "neovim"
brew "plotutils"
brew "pstoedit"
brew "qhull"
brew "octave"
brew "openvpn"
brew "pandoc"
brew "postgresql", restart_service: true
brew "sfcgal"
brew "postgis"
brew "pwsafe"
brew "pyenv"
brew "qt"
brew "ruby-build"
brew "rbenv"
brew "rbenv-default-gems"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "rust"
brew "screenresolution"
brew "slackcat"
brew "smartmontools"
brew "syncthing"
brew "texinfo"
brew "tmux"
brew "trash"
brew "tree"
brew "unixodbc"
brew "utf8proc"
brew "watchman"
brew "wget"
brew "yarn"
brew "zsh"
brew "heroku/brew/heroku"
brew "kylef/formulae/swiftenv"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "android-file-transfer"
cask "android-studio"
cask "aquaterm"
cask "arduino"
cask "calibre"
cask "chromium"
cask "docker"
cask "firefox"
cask "flux"
cask "free-ruler"
cask "google-chrome"
cask "iterm2"
cask "keepassxc"
cask "libreoffice"
cask "lmms"
cask "macdown"
cask "macpass"
cask "ngrok"
cask "skype-for-business"
cask "steam"
cask "tcl"
cask "transmission"
cask "unity"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vlc"
cask "caskroom/fonts/font-hack"
cask "caskroom/fonts/font-hack-nerd-font"
cask "caskroom/fonts/font-lato"
cask "caskroom/fonts/font-source-code-pro"
cask "caskroom/fonts/font-sourcecodepro-nerd-font"
cask "caskroom/fonts/font-work-sans"
cask "caskroom/versions/firefoxdeveloperedition"
cask "caskroom/versions/java8"
mas "1Blocker", id: 1107421413
mas "2Do", id: 477670270
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Airmail 3", id: 918858936
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft OneNote", id: 784801555
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RadarScope", id: 432027450
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "TweetDeck", id: 485812721
mas "Twitter", id: 409789998
mas "Xcode", id: 497799835
