#!/usr/bin/env bash
ln -sf $PWD/.aprc ~/.aprc
ln -sf $PWD/.cobra.yaml ~/.cobra.yaml
ln -sf $PWD/.ctags ~/.ctags
ln -sf $PWD/.gemrc ~/.gemrc
ln -sf $PWD/.gitconfig ~/.gitconfig
ln -sf $PWD/.gitignore_global ~/.gitignore_global
ln -sf $PWD/.git_template ~/.git_template
ln -sf $PWD/.irbrc ~/.irbrc
ln -sf $PWD/.pryrc ~/.pryrc
ln -sf $PWD/.ssh_config ~/.ssh/config
ln -sf $PWD/.tmux.conf ~/.tmux.conf
ln -sf $PWD/.vimrc ~/.vimrc
ln -sf $PWD/.zshenv ~/.zshenv
ln -sf $PWD/.zshrc ~/.zshrc
if which rbenv > /dev/null; then ln -sf $PWD/default-gems $(echo $HOME/.rbenv)/default-gems; fi
