#!/usr/bin/env bash
set -x
set -e

if [ ! -d ~/.config ]; then mkdir ~/.config; fi

# use ~/.vim and ~/.vimrc with neovim
ln -sfh ~/.vim ~/.config/nvim
ln -sf ~/.vim/init.vim ~/.vimrc

ln -sf $PWD/.aprc ~/.aprc
if [ ! -d ~/.bundle ]; then mkdir ~/.bundle; fi
ln -sf $PWD/bundle_config ~/.bundle/config
ln -sf $PWD/.cobra.yaml ~/.cobra.yaml
ln -sf $PWD/.ctags ~/.ctags
ln -sf $PWD/.eslintrc.js ~/.eslintrc.js
ln -sf $PWD/.gemrc ~/.gemrc
ln -sf $PWD/.gitconfig ~/.gitconfig
ln -sf $PWD/.gitignore_global ~/.gitignore_global
ln -sfh $PWD/.git_template ~/.git_template
ln -sf $PWD/.ignore ~/.ignore
ln -sf $PWD/.irbrc ~/.irbrc
ln -sfh $PWD/powerline ~/.config/powerline
ln -sf $PWD/.pryrc ~/.pryrc
ln -sf $PWD/.railsrc ~/.railsrc
ln -sf $PWD/.ssh_config ~/.ssh/config
ln -sf $PWD/.tern-config ~/.tern-config
ln -sf $PWD/.tigrc ~/.tigrc
ln -sf $PWD/.tmux.conf ~/.tmux.conf
ln -sf $PWD/.vimrc ~/.vimrc
ln -sf $PWD/.xvimrc ~/.xvimrc
ln -sf $PWD/.zshenv ~/.zshenv
ln -sf $PWD/.zshrc ~/.zshrc

if [ ! -d ~/bin ]; then mkdir ~/bin; fi
if [ ! -d ~/.vim/swapfiles ]; then mkdir ~/.vim/swapfiles; fi
ln -sf $PWD/bin/imgcat ~/bin/imgcat
ln -sf $PWD/bin/imgls ~/bin/imgls
ln -sf $PWD/bin/delete_branches ~/bin/delete_branches

if ! command -v rbenv &> /dev/null
then
  echo "rbenv not installed, skipping default-gems."
else
  ln -sf $PWD/default-gems $(echo $HOME/.rbenv)/default-gems
fi

if ! command -v brew &> /dev/null
then
  echo "homebrew not installed, skipping font installation."
else
  brew update && \
    brew tap homebrew/cask-fonts && \
    brew install font-hack && \
    brew install font-hack-nerd-font
fi
