#!/usr/bin/env bash
set -e

red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
blue="\033[0;34m"
bold="\033[1m"
reset="\033[0m"

# submodules are used in zsh_custom for plugins/themes
git submodule update --init --recursive

if [ ! -f .gitconfig.inc ]; then
  echo -e "${bold}${yellow}Creating .gitconfig.inc from template...${reset}"
  cp .gitconfig.inc.template .gitconfig.inc
  echo -e  "${bold}${red}Edit .gitconfig.inc before continuing.${reset}"
  exit 1
fi

if [ ! -d ~/.config ]; then
  echo -e "${blue}Creating ~/.config directory...${reset}"
  mkdir ~/.config
fi

set -x
# use ~/.vim with neovim (.vimrc is sourced via init.vim)
ln -sfh ~/.vim ~/.config/nvim

ln -sf $PWD/.aprc ~/.aprc
set +x

if [ ! -d ~/.bundle ]; then
  echo -e "${blue}Creating ~/.bundle directory...${reset}"
  mkdir ~/.bundle
fi

set -x
ln -sf $PWD/.aerospace.toml ~/.aerospace.toml
ln -sf $PWD/bundle_config ~/.bundle/config
ln -sf $PWD/.cobra.yaml ~/.cobra.yaml
ln -sf $PWD/.ctags ~/.ctags
ln -sf $PWD/.eslintrc.js ~/.eslintrc.js
ln -sf $PWD/.gemrc ~/.gemrc
ln -sf $PWD/.gitconfig ~/.gitconfig
ln -sf $PWD/.gitconfig.inc ~/.gitconfig.inc
ln -sf $PWD/.gitignore_global ~/.gitignore_global
ln -sfh $PWD/.git_template ~/.git_template
ln -sf $PWD/.ignore ~/.ignore
ln -sf $PWD/init.vim ~/.vim/init.vim
ln -sf $PWD/.irbrc ~/.irbrc
ln -sfh $PWD/powerline ~/.config/powerline
ln -sf $PWD/.pryrc ~/.pryrc
ln -sf $PWD/.railsrc ~/.railsrc
ln -sf $PWD/.ssh_config ~/.ssh/config
ln -sf $PWD/.tern-config ~/.tern-config
ln -sf $PWD/.tigrc ~/.tigrc
ln -sf $PWD/.tmux.conf ~/.tmux.conf
ln -sf $PWD/.vimrc ~/.vimrc
ln -sf $PWD/.xvimrc ~/.xvimrc
ln -sf $PWD/.zprofile ~/.zprofile
ln -sf $PWD/.zshenv ~/.zshenv
ln -sf $PWD/.zshrc ~/.zshrc
set +x

if [ ! -d ~/.vim/swapfiles ]; then
  echo -e "${blue}Creating ~/.vim/swapfiles directory...${reset}"
  mkdir ~/.vim/swapfiles
fi

if [ ! -d ~/bin ]; then
  echo -e "${blue}Creating ~/bin directory...${reset}"
  mkdir ~/bin
fi

set -x
ln -sf $PWD/bin/imgcat ~/bin/imgcat
ln -sf $PWD/bin/imgls ~/bin/imgls
ln -sf $PWD/bin/delete_branches ~/bin/delete_branches
set +x

if ! command -v rbenv &> /dev/null
then
  echo -e "${bold}${yellow}rbenv not installed, skipping default-gems.${reset}"
else
  echo -e "Assigning default-gems for rbenv."
  set -x
  ln -sf $PWD/default-gems "$HOME/.rbenv/default-gems"
  set +x
fi

# Xcode custom editor theme
xcode_theme_path=~/Library/Developer/Xcode/UserData/FontAndColorThemes/
if [ -d $xcode_theme_path ]; then
  echo -e "${blue}Installing custom Xcode theme...${reset}"
  set -x
  cp Solarized-Dark-Hacked.xccolortheme $xcode_theme_path
  set +x
else
  echo -e "${bold}${yellow}Xcode not installed, skipping theme.${reset}"
fi

echo -e "${green}Done! Next steps:${reset}"
echo -e "- Install a nerd font and configure terminal to use it, see ${red}install-fonts${reset}."
echo -e "- Add a .gitconfig in ~/work to override email and signing key (optional)."
